# Generated by Django 3.0.3 on 2020-03-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste2currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('uuid', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('wtype', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('Createdby', models.CharField(default='', max_length=200)),
                ('Owndedby', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='Ecoins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='Fcoins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
