# Generated by Django 3.0.3 on 2020-03-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste2currency', '0003_auto_20200327_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waste',
            old_name='Owndedby',
            new_name='Ownedby',
        ),
    ]
